/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.unpas.ewhale.approval_masyarakat;

import id.ac.unpas.ewhale.dao.MasyarakatDao;
import id.ac.unpas.ewhale.main.TambahMasyarakat;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class MasyarakatFrame extends javax.swing.JFrame {
    private MasyarakatModelTable modelTable;
    private MasyarakatDao masyarakatDao;
    private MasyarakatFrame masyarakatFrame;
    private List<Masyarakat> masyarakatList;
    private TambahMasyarakat tambahMasyarakat;

    /**
     * Creates new form MasyarakatFrame
     */
    public MasyarakatFrame(MasyarakatDao masyarakatDao) {
        this.masyarakatDao = masyarakatDao;
        this.masyarakatList = this.masyarakatDao.findAll();
        this.modelTable = new MasyarakatModelTable(masyarakatList);
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        approvalregistrasi = new javax.swing.JLabel();
        datamaster = new javax.swing.JLabel();
        iconMasyarakat = new javax.swing.JLabel();
        masyarakatButton = new javax.swing.JButton();
        iconKurir = new javax.swing.JLabel();
        kurirButton = new javax.swing.JButton();
        iconJeniskat = new javax.swing.JLabel();
        jeniskatButton = new javax.swing.JButton();
        iconKonversi = new javax.swing.JLabel();
        konversiButton = new javax.swing.JButton();
        iconDropbox = new javax.swing.JLabel();
        dropboxButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        tambahmasyarakatButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMasyarakat = new javax.swing.JTable();
        terimaMasyarakat = new javax.swing.JButton();
        tolakMasyarakat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(37, 43, 59));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));

        approvalregistrasi.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        approvalregistrasi.setForeground(new java.awt.Color(204, 204, 204));
        approvalregistrasi.setText("APPROVAL REGISTRASI");

        datamaster.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        datamaster.setForeground(new java.awt.Color(204, 204, 204));
        datamaster.setText("DATAMASTER");

        masyarakatButton.setBackground(new java.awt.Color(37, 43, 59));
        masyarakatButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        masyarakatButton.setForeground(new java.awt.Color(255, 255, 255));
        masyarakatButton.setText("Approval Masyarakat");
        masyarakatButton.setBorderPainted(false);
        masyarakatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masyarakatButtonActionPerformed(evt);
            }
        });

        kurirButton.setBackground(new java.awt.Color(37, 43, 59));
        kurirButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kurirButton.setForeground(new java.awt.Color(255, 255, 255));
        kurirButton.setText("Approval Kurir");
        kurirButton.setBorderPainted(false);
        kurirButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kurirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurirButtonActionPerformed(evt);
            }
        });

        jeniskatButton.setBackground(new java.awt.Color(37, 43, 59));
        jeniskatButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jeniskatButton.setForeground(new java.awt.Color(255, 255, 255));
        jeniskatButton.setText("Jenis dan Kategori");
        jeniskatButton.setBorderPainted(false);
        jeniskatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeniskatButtonActionPerformed(evt);
            }
        });

        konversiButton.setBackground(new java.awt.Color(37, 43, 59));
        konversiButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        konversiButton.setForeground(new java.awt.Color(255, 255, 255));
        konversiButton.setText("Konversi Poin");
        konversiButton.setBorderPainted(false);
        konversiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversiButtonActionPerformed(evt);
            }
        });

        dropboxButton.setBackground(new java.awt.Color(37, 43, 59));
        dropboxButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dropboxButton.setForeground(new java.awt.Color(255, 255, 255));
        dropboxButton.setText("Drop Box");
        dropboxButton.setBorderPainted(false);
        dropboxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropboxButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(approvalregistrasi))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(datamaster))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(iconKurir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kurirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(iconMasyarakat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(masyarakatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(iconJeniskat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jeniskatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconDropbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dropboxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(konversiButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(approvalregistrasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconMasyarakat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masyarakatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconKurir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kurirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(datamaster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconJeniskat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jeniskatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(iconKonversi))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(konversiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconDropbox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropboxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 209, 550));

        jPanel3.setOpaque(false);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));

        tambahmasyarakatButton.setBackground(new java.awt.Color(51, 102, 0));
        tambahmasyarakatButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tambahmasyarakatButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahmasyarakatButton.setText("Tambah Data");
        tambahmasyarakatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahmasyarakatButtonActionPerformed(evt);
            }
        });

        tableMasyarakat.setModel(modelTable);
        jScrollPane1.setViewportView(tableMasyarakat);

        terimaMasyarakat.setBackground(new java.awt.Color(51, 102, 0));
        terimaMasyarakat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        terimaMasyarakat.setText("Terima");
        terimaMasyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terimaMasyarakatActionPerformed(evt);
            }
        });

        tolakMasyarakat.setBackground(new java.awt.Color(242, 0, 0));
        tolakMasyarakat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tolakMasyarakat.setForeground(new java.awt.Color(255, 255, 255));
        tolakMasyarakat.setText("Tolak");
        tolakMasyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tolakMasyarakatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(tambahmasyarakatButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                        .addComponent(terimaMasyarakat)
                        .addGap(35, 35, 35)
                        .addComponent(tolakMasyarakat)
                        .addGap(121, 121, 121))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahmasyarakatButton)
                    .addComponent(terimaMasyarakat)
                    .addComponent(tolakMasyarakat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 73, 790, 552));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 625));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setModelTable(MasyarakatModelTable modelTable) {
        // Set this.id dengan parameter id
        this.modelTable = modelTable;
    }
    
    // Dapatkan nilai dari id
    public MasyarakatModelTable getModelTable() {
        // Kembalikan nilai dari this.id
        return this.modelTable;
    }  
    
    private void tambahmasyarakatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahmasyarakatButtonActionPerformed
        // TODO add your handling code here:
        tambahMasyarakat = new TambahMasyarakat();
        tambahMasyarakat.setVisible(true);
    }//GEN-LAST:event_tambahmasyarakatButtonActionPerformed

    private void masyarakatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masyarakatButtonActionPerformed
        // TODO add your handling code here:
        masyarakatDao = new MasyarakatDao();
        masyarakatFrame = new MasyarakatFrame(masyarakatDao);
        masyarakatFrame.setVisible(true);
    }//GEN-LAST:event_masyarakatButtonActionPerformed

    private void kurirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurirButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kurirButtonActionPerformed

    private void jeniskatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeniskatButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jeniskatButtonActionPerformed

    private void konversiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversiButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_konversiButtonActionPerformed

    private void dropboxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropboxButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropboxButtonActionPerformed

    private void terimaMasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terimaMasyarakatActionPerformed
        // TODO add your handling code here:
        int row = this.tableMasyarakat.getSelectedRow();
        int column = this.tableMasyarakat.getSelectedColumn();
        int response = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menerima masyararakat ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
     
        if (row == -1 || column == -1) {
          return;
        } else {
          String newValue = (String) this.tableMasyarakat.getModel().getValueAt(row, column);
     
          Masyarakat id = new Masyarakat();

          String col = "";

          switch (column) {
                case 0:
                    col = "namaMasyarakat";
                    break;
                case 1:
                    col = "noTeleponMasyarakat";
                    break;
                case 2:
                    col = "alamatMasyarakat";
                    break;
                default:
                    System.out.println("Kolom tidak ditemukan");
                    break;
            }
           if(response==JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Masyarakat berhasil diterima");
            
                id = this.masyarakatDao.select(col, newValue);
                
                 this.delete(id);
                 this.masyarakatDao.delete(id);
                 
           }else if(response==JOptionPane.NO_OPTION){
                   JOptionPane.showMessageDialog(this, "Masyarakat gagal diterima");
                   
           }else if(response==JOptionPane.CLOSED_OPTION) {
                System.out.println("Closed");
           }
           
      }
    }//GEN-LAST:event_terimaMasyarakatActionPerformed
    
    // Method untuk menghapus permintaan ke tableModel
    public void delete(Masyarakat masyarakat) {
        // Tambahkan permintaan ke tableModel
        modelTable.delete(masyarakat);
    }
    
    
    private void tolakMasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tolakMasyarakatActionPerformed
        // TODO add your handling code here:
         int row = this.tableMasyarakat.getSelectedRow();
         int column = this.tableMasyarakat.getSelectedColumn();
         int response = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin menolak masyararakat ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (row == -1 || column == -1) {
          return;
        } else {
          String newValue = (String) this.tableMasyarakat.getModel().getValueAt(row, column);
     
          Masyarakat id = new Masyarakat();

          String col = "";

          switch (column) {
                case 0:
                    col = "namaMasyarakat";
                    break;
                case 1:
                    col = "noTeleponMasyarakat";
                    break;
                case 2:
                    col = "alamatMasyarakat";
                    break;
                default:
                    System.out.println("Kolom tidak ditemukan");
                    break;
            }
             if(response==JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "Masyarakat berhasil ditolak");
            
                id = this.masyarakatDao.select(col, newValue);
                
                 this.delete(id);
                 this.masyarakatDao.delete(id);
                 
             }else if(response==JOptionPane.NO_OPTION){
                   JOptionPane.showMessageDialog(this, "Masyarakat gagal ditolak");
                   
             }else if(response==JOptionPane.CLOSED_OPTION) {
                System.out.println("Closed");
             }
        }
    }//GEN-LAST:event_tolakMasyarakatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel approvalregistrasi;
    private javax.swing.JLabel datamaster;
    private javax.swing.JButton dropboxButton;
    private javax.swing.JLabel iconDropbox;
    private javax.swing.JLabel iconJeniskat;
    private javax.swing.JLabel iconKonversi;
    private javax.swing.JLabel iconKurir;
    private javax.swing.JLabel iconMasyarakat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jeniskatButton;
    private javax.swing.JButton konversiButton;
    private javax.swing.JButton kurirButton;
    private javax.swing.JButton masyarakatButton;
    private javax.swing.JTable tableMasyarakat;
    private javax.swing.JButton tambahmasyarakatButton;
    private javax.swing.JButton terimaMasyarakat;
    private javax.swing.JButton tolakMasyarakat;
    // End of variables declaration//GEN-END:variables
}
