/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.unpas.ewhale.main;

/**
 *
 * @author Haykal
 */

import id.ac.unpas.ewhale.konversi_poin.KonversiPoin;
import id.ac.unpas.ewhale.konversi_poin.KonversiPoinFrame;
import id.ac.unpas.ewhale.konversi_poin.KonversiPoinModelTable;
import id.ac.unpas.ewhale.dao.KonversiPoinDao;
import java.util.List;

public class TambahKonversiPoin extends javax.swing.JFrame {

    private KonversiPoinModelTable modelTable;
    private KonversiPoinDao konversiPoinDao;
    private KonversiPoinFrame konversiPoinFrame;
    private List<KonversiPoin> konversipoinList;
    
    /**
     * Creates new form TambahKonversiPoin
     */
    public TambahKonversiPoin() {
      this.konversiPoinDao = new KonversiPoinDao();
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jenisTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kategoriTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        submitKonversiPoinButton = new javax.swing.JButton();
        poinTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tambah Data Konversi Sampah");

        jenisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Jenis");

        kategoriTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Kategori");

        submitKonversiPoinButton.setBackground(new java.awt.Color(0, 153, 0));
        submitKonversiPoinButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitKonversiPoinButton.setForeground(new java.awt.Color(255, 255, 255));
        submitKonversiPoinButton.setText("Submit");
        submitKonversiPoinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitKonversiPoinButtonActionPerformed(evt);
            }
        });

        poinTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poinTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Poin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(142, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitKonversiPoinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(poinTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jenisTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(kategoriTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))))
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kategoriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addComponent(submitKonversiPoinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addData(KonversiPoin konversipoin){
        this.konversiPoinDao = new KonversiPoinDao();
        konversiPoinFrame = new KonversiPoinFrame( konversiPoinDao);
        this.konversipoinList = this.konversiPoinDao.findAll();
        KonversiPoinModelTable konversiPoinModelTable = new KonversiPoinModelTable(konversipoinList);
        konversiPoinFrame.setModelTable(konversiPoinModelTable);
        jenisTextField.setText("");
        kategoriTextField.setText("");
        poinTextField.setText("");
    }
    
    
    
    
    private void jenisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisTextFieldActionPerformed

    private void kategoriTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriTextFieldActionPerformed

    private void submitKonversiPoinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitKonversiPoinButtonActionPerformed
        // TODO add your handling code here:
        String jenisSampah = this.jenisTextField.getText();
        String kategoriSampah = this.kategoriTextField.getText();
        String poinSampah = this.poinTextField.getText();

        KonversiPoin konversiPoin = new KonversiPoin();
        konversiPoin.setjenisSampah(jenisSampah);
        konversiPoin.setkategoriSampah(kategoriSampah);
        konversiPoin.setpoinSampah(poinSampah);
                
        

        this.konversiPoinDao.insert(konversiPoin);
        this.addData(konversiPoin);
    }//GEN-LAST:event_submitKonversiPoinButtonActionPerformed

    private void poinTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poinTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poinTextFieldActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jenisTextField;
    private javax.swing.JTextField kategoriTextField;
    private javax.swing.JTextField poinTextField;
    private javax.swing.JButton submitKonversiPoinButton;
    // End of variables declaration//GEN-END:variables
}
