/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.unpas.ewhale.main;

import id.ac.unpas.ewhale.drop_box.DropBox;
import id.ac.unpas.ewhale.drop_box.DropBoxFrame;
import id.ac.unpas.ewhale.drop_box.DropBoxModelTable;
import id.ac.unpas.ewhale.dao.DropBoxDao;
import java.util.List;

/**
 *
 * @author Afandi
 */
public class UbahDropBox extends javax.swing.JFrame {

    /**
     * Creates new form UbahJenisKat
     */
    
    private DropBoxModelTable modelTable;
    private DropBoxDao dropBoxDao;
    private DropBoxFrame dropBoxFrame;
    private List<DropBox> dropBoxList;
    private DropBox dropBox;
    
    public UbahDropBox(DropBox dropBox) {
        initComponents();
        this.dropBox = dropBox;
        this.namaMasyarakatTextField.setText(this.dropBox.getnamaMasyarakat());
        this.alamatMasyarakatTextField.setText(this.dropBox.getalamatMasyarakat());
        this.jenisTextField.setText(this.dropBox.getjenisSampah());
        this.kategoriTextField.setText(this.dropBox.getkategoriSampah());
        this.poinTextField.setText(this.dropBox.getpoinSampah());
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
    }

    public void updateData(DropBox dropBox) {
        this.dropBoxDao = new DropBoxDao();
        dropBoxFrame = new DropBoxFrame(dropBoxDao);
        this.dropBoxList = this.dropBoxDao.findAll();
        DropBoxModelTable dropBoxModelTable = new DropBoxModelTable(dropBoxList);
        dropBoxFrame.setModelTable(dropBoxModelTable);
        namaMasyarakatTextField.setText("");
        alamatMasyarakatTextField.setText(" ");
        jenisTextField.setText("");
        kategoriTextField.setText(" ");
        poinTextField.setText(" ");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namaMasyarakatTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jenisTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        submitJenisKatButton = new javax.swing.JButton();
        alamatMasyarakatTextField = new javax.swing.JTextField();
        kategoriTextField = new javax.swing.JTextField();
        poinTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ubah Data DropBox");

        namaMasyarakatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaMasyarakatTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Masyarakat");

        jenisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Kategori Sampah");

        submitJenisKatButton.setBackground(new java.awt.Color(0, 153, 0));
        submitJenisKatButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitJenisKatButton.setText("Submit");
        submitJenisKatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJenisKatButtonActionPerformed(evt);
            }
        });

        alamatMasyarakatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatMasyarakatTextFieldActionPerformed(evt);
            }
        });

        kategoriTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriTextFieldActionPerformed(evt);
            }
        });

        poinTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poinTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Alamat Masyarakat");

        jLabel5.setText("Poin Sampah");

        jLabel6.setText("Jenis Sampah");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitJenisKatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jenisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 54, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(poinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kategoriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(namaMasyarakatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(alamatMasyarakatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(62, 62, 62)))))
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaMasyarakatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamatMasyarakatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategoriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(poinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(submitJenisKatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaMasyarakatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaMasyarakatTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namaMasyarakatTextFieldActionPerformed

    private void jenisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jenisTextFieldActionPerformed

    private void submitJenisKatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJenisKatButtonActionPerformed
        // TODO add your handling code here:
        this.dropBoxDao = new DropBoxDao();
        String namaMasyarakat = this.namaMasyarakatTextField.getText();
        String alamatMasyarakat = this.alamatMasyarakatTextField.getText();
        String jenisSampah = this.jenisTextField.getText();
        String kategoriSampah = this.kategoriTextField.getText();
        String poinSampah = this.poinTextField.getText();
 
        DropBox dropBox = new DropBox();
        dropBox.setidDropBox(this.dropBox.getidDropBox());
        dropBox.setnamaMasyarakat(namaMasyarakat);
        dropBox.setalamatMasyarakat(alamatMasyarakat);
        dropBox.setjenisSampah(jenisSampah);
        dropBox.setkategoriSampah(kategoriSampah);
        dropBox.setpoinSampah(poinSampah);

        
        this.dropBoxDao.update(dropBox);
        this.updateData(dropBox);
    }//GEN-LAST:event_submitJenisKatButtonActionPerformed

    private void alamatMasyarakatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatMasyarakatTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatMasyarakatTextFieldActionPerformed

    private void kategoriTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriTextFieldActionPerformed

    private void poinTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poinTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poinTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatMasyarakatTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jenisTextField;
    private javax.swing.JTextField kategoriTextField;
    private javax.swing.JTextField namaMasyarakatTextField;
    private javax.swing.JTextField poinTextField;
    private javax.swing.JButton submitJenisKatButton;
    // End of variables declaration//GEN-END:variables
}
